In [ ]:
from google.colab import drive # FLOURIDE CONTENT PREDICTION
drive.mount('/MinorProjectDatasets/')

Mounted at /MinorProjectDatasets/


In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [ ]:
data_frame = pd.read_excel('/MinorProjectDatasets/Predictor Dataset.xlsx')
data_frame

FileNotFoundError: ignored

In [ ]:
X = data_frame.iloc[:, 2:8].values
Y = data_frame.iloc[:, 8].values
print("The Predictor Variables Dataset is :\n", X)
print("The Labelled Dataset is :\n", Y)

The Predictor Variables Dataset is :
 [[1.81400e+03 5.51055e+00 6.78900e+03 1.23200e+03 4.00000e+01 8.29000e+00]
 [1.89900e+03 5.26334e+00 1.59690e+04 3.03400e+03 4.00000e+01 7.91000e+00]
 [2.09600e+03 4.76942e+00 3.74400e+03 7.85000e+02 1.60000e+01 8.06000e+00]
 ...
 [2.00500e+03 4.98488e+00 6.59500e+03 1.32300e+03 1.70000e+01 7.93000e+00]
 [2.04800e+03 4.88160e+00 6.92700e+03 1.41900e+03 1.70000e+01 8.58000e+00]
 [2.23700e+03 4.46822e+00 4.21800e+03 9.44000e+02 4.00000e+01 7.08000e+00]]
The Labelled Dataset is :
 [0.42 0.11 0.54 ... 3.78 3.82 0.1 ]


In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn import metrics

In [ ]:
rfr_model = RandomForestRegressor(n_estimators = 250, random_state = 0)
rfr_model.fit(X_train, Y_train)
Y_pred = rfr_model.predict(X_test)

In [ ]:
print('Mean Absolute Error:', metrics.mean_absolute_error(Y_test, Y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(Y_test, Y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(Y_test, Y_pred)))

Mean Absolute Error: 0.40358197231950044
Mean Squared Error: 1.4897616463884689
Root Mean Squared Error: 1.2205579242250115


In [ ]:
rfr_model = RandomForestRegressor(n_estimators = 500, random_state = 0)
rfr_model.fit(X_train, Y_train)
Y_pred = rfr_model.predict(X_test)

In [ ]:
print('Mean Absolute Error:', metrics.mean_absolute_error(Y_test, Y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(Y_test, Y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(Y_test, Y_pred)))

Mean Absolute Error: 0.4026013032931348
Mean Squared Error: 1.4796434433061434
Root Mean Squared Error: 1.2164059533338956


In [ ]:
xgr_model = XGBRegressor(n_estimators = 250)
xgr_model.fit(X_train, Y_train)
Y_pred = xgr_model.predict(X_test)

In [ ]:
print('Mean Absolute Error:', metrics.mean_absolute_error(Y_test, Y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(Y_test, Y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(Y_test, Y_pred)))

Mean Absolute Error: 0.41722835516141327
Mean Squared Error: 1.3745739584516214
Root Mean Squared Error: 1.1724222611549227


In [ ]:
xgr_model = XGBRegressor(n_estimators = 500)
xgr_model.fit(X_train, Y_train)
Y_pred = xgr_model.predict(X_test)

In [ ]:
print('Mean Absolute Error:', metrics.mean_absolute_error(Y_test, Y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(Y_test, Y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(Y_test, Y_pred)))

Mean Absolute Error: 0.4154402872945621
Mean Squared Error: 1.3755262702219022
Root Mean Squared Error: 1.1728283208645254


In [ ]:
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

In [ ]:
X = data_frame.iloc[:, 2:8].values
Y = data_frame.iloc[:, 9].values
print("The Predictor Variables Dataset is :\n", X)
print("The Labelled Dataset is :\n", Y)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

The Predictor Variables Dataset is :
 [[1.81400e+03 5.51055e+00 6.78900e+03 1.23200e+03 4.00000e+01 8.29000e+00]
 [1.89900e+03 5.26334e+00 1.59690e+04 3.03400e+03 4.00000e+01 7.91000e+00]
 [2.09600e+03 4.76942e+00 3.74400e+03 7.85000e+02 1.60000e+01 8.06000e+00]
 ...
 [2.00500e+03 4.98488e+00 6.59500e+03 1.32300e+03 1.70000e+01 7.93000e+00]
 [2.04800e+03 4.88160e+00 6.92700e+03 1.41900e+03 1.70000e+01 8.58000e+00]
 [2.23700e+03 4.46822e+00 4.21800e+03 9.44000e+02 4.00000e+01 7.08000e+00]]
The Labelled Dataset is :
 [0 0 0 ... 1 1 0]


In [ ]:
rfc_model = RandomForestClassifier(n_estimators = 250, random_state = 0)
rfc_model.fit(X_train, Y_train)
Y_pred = rfc_model.predict(X_test)

In [ ]:
print('Accuracy of Random Forest Classifier is -', metrics.accuracy_score(Y_test, Y_pred, normalize = True)*100)

Accuracy of Random Forest Classifier is - 85.04259393779304


In [ ]:
rfc_model = RandomForestClassifier(n_estimators = 500, random_state = 0)
rfc_model.fit(X_train, Y_train)
Y_pred = rfc_model.predict(X_test)

In [ ]:
print('Accuracy of Random Forest Classifier is -', metrics.accuracy_score(Y_test, Y_pred, normalize = True)*100)

Accuracy of Random Forest Classifier is - 85.02278280393581


In [ ]:
xgc_model = XGBClassifier(n_estimators = 250)
xgc_model.fit(X_train, Y_train)
Y_pred = xgc_model.predict(X_test)

In [ ]:
print("Accuracy of XGBoost Classifier is -", metrics.accuracy_score(Y_test, Y_pred)*100)

Accuracy of XGBoost Classifier is - 84.55391930264808


In [ ]:
xgc_model = XGBClassifier(n_estimators = 500)
xgc_model.fit(X_train, Y_train)
Y_pred = xgc_model.predict(X_test)

In [ ]:
print("Accuracy of XGBoost Classifier is -", metrics.accuracy_score(Y_test, Y_pred)*100)

Accuracy of XGBoost Classifier is - 84.73221950736314
